src/br/com/project/bean/view/CedulaBeanView.java
package br.com.project.bean.view;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.framework.interfac.crud.InterfaceCrud;
import br.com.project.bean.geral.BeanManagedViewAbstract;
import br.com.project.geral.controller.CedulaController;

@Controller
@Scope(value = "session")
@ManagedBean(name = "cedulaBeanView")
public class CedulaBeanView extends BeanManagedViewAbstract {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Autowired
	private CedulaController cedulaController;
	
	public List<SelectItem> getCedulas() throws Exception {
		return cedulaController.getListCedula();
	}

	@Override
	protected Class<?> getClassImplement() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected InterfaceCrud<?> getController() {
		// TODO Auto-generated method stub
		return null;
	}


}

WebContent/recarga/rec_cedulas.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:sec="http://www.springframework.org/security/facelets/tags"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:p="http://primefaces.org/ui">

	<ui:composition template="/templates/templatePrincipal.xhtml">
		<ui:define name="corpo">
			<h:form id="formRecCedulas" prependId="false">
				<p:panel header="Reabastecer Cédulas do Caixa Eletrônico" id="panelRecCedulas">
				<br/>
					<h:panelGrid id="gridRecCedulas" columns="4">
						<p:inputText id="qtdeCedulas" style="width: 30px" required="true" requiredMessage="Informe a quantidade de cédulas para abastecimento"/>
						<p:message for="qtdeCedulas"/>
						<h:outputLabel value="  Cédulas de: "/>
						<p:selectOneMenu style="width:170px">
				            <f:selectItem itemLabel="Selecione o tipo de cédula" itemValue="" />
				            <f:selectItems value="#{cedulaBeanView.cedulas}" />
				        </p:selectOneMenu>
				        <h:outputLabel/>
					</h:panelGrid>
				</p:panel>
				<br/>
				<p:commandButton value="Reabastecer" ajax="true" immediate="false"/>
			</h:form>	
		</ui:define>
	</ui:composition>
</html>