src/br/com/project/bean/view/UsuarioBeanView.java
package br.com.project.bean.view;

import java.util.Date;

import javax.faces.bean.ManagedBean;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.framework.interfac.crud.InterfaceCrud;
import br.com.project.bean.geral.BeanManagedViewAbstract;
import br.com.project.geral.controller.UsuarioController;
import br.com.project.model.classes.Usuario;

@Controller
@Scope(value = "session")
@ManagedBean(name = "usuarioBeanView")
public class UsuarioBeanView extends BeanManagedViewAbstract{
	
	@Autowired
	private ContextoBean contextoBean;

	private static final long serialVersionUID = 1L;
	
	@Autowired
	private UsuarioController usuarioController;

	public String getUsuarioLogadoSecurity() {
		return contextoBean.getAuthentication().getName();
	}
	
	public Date getUltimoAcesso() throws Exception {
		return contextoBean.getUsuarioLogado().getUltimoAcesso();
	}


	@Override
	protected Class<Usuario> getClassImplement() {
		return Usuario.class;
	}

	@Override
	protected InterfaceCrud<Usuario> getController() {
		return usuarioController;
	}

}

WebContent/templates/barraProgresso.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:composition>
		
		<p:ajaxStatus id="ajaxStatus" onstart="statusDialog.show()" onsuccess="statusDialog.hide()"/>
	
		<p:dialog id="dialogAjaxStatus" model="true" widgetVar="statusDialog" height="200px;" width="200px" 
		header="Processando" footer="Aguarde..." draggable="false" appendTo="@(body)" dynamic="false" resizable="false"
		closable="false">
		
			<h:graphicImage library="img" name="ajax-loader.gif" id="imgAjaxLoader" styleClass="bordaImagem"/>
		
		</p:dialog>
		
		<p:dialog id="dialogAjaxStatusError" modal="true" widgetVar="statusDialogError" height="200px" width="200px" resizable="false"
		header="Erro ao processar." footer="Erro" draggable="false" closable="true">
			<h:graphicImage library="img" name="error.png" id="imgAjaxLoaderError" styleClass="bordaImagem"/>
		</p:dialog>
		
	
	</ui:composition>

</html>

WebContent/templates/templatePrincipal.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sec="http://www.springframework.org/security/facelets/tags"
	xmlns:p="http://primefaces.org/ui">
<sec:isAuthenticated>

	<h:head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title><ui:insert name="titulo">Caixa Eletrônico</ui:insert></title>

	<h:outputScript name="primefaces.js" library="primefaces" id="jsPrime" />
	<h:outputScript name="jquery.js" library="primefaces/jquery" id="jsJquery" />
	<h:outputScript name="jquery-plugins.js" library="primefaces/jquery" id="jsJqueryPlugin" />
	<h:outputScript name="jquery.cookie.js" library="javascript" id="jsJaqueryCookie" />
	<h:outputStylesheet name="jquery-ui.css" library="primefaces/jquery/ui"	id="jsJqueryUi" />
	<h:outputStylesheet name="primefaces.css" library="primefaces" id="jdPrimeCss" />
	<h:outputScript name="jquery.maskMoney.min.js" library="javascript"	id="jsMaskMoneySistema" />
	<h:outputScript name="jquery.maskedinput.js" library="javascript" id="jsMaskInputSistema" />
	<h:outputScript name="scripty.js" library="javascript"	id="jsScriptSistema" />
	<h:outputStylesheet name="estilo.css" library="css"	id="cssStiloSistema" />
	

	
}

</h:head>
	
<h:form id="formTemplate" prependId="false">
	<h:outputStylesheet name="estilo.css" library="css" id="cssStyleSistema"/>
	
	<h:body>
		<script type="text/javascript" charset="UTF-8">
			$.noConflict();

			$(document).keydown(function(e) {
				if (e.which == 116){
					return 116;
					}
			}); 
		</script>
		
		<ui:include src="/templates/barraProgresso.xhtml" />
		<div id="msgError">
			<p:growl id="msg" showDetail="false" sticky="true" redisplay="true" autoUpdate="true"/>
			<p:tooltip id="toolTipFocus" globalSelector="a, :input, :button" showEvent="focus" hideEvent="blur"/>
		</div>
		
		<div id="container">
			<div id="topo">
				<span style="position: absolute;left: 20px;top: 14px" id="spanLogo">
					<h:graphicImage library="img" name="logo.png" id="logoImg" styleClass="bordaImagem"/>
				</span>
				
				<span id="dadoslogin"> Usuário: #{usuarioBeanView.usuarioLogadoSecurity}
					<br id="quebraUser"/>
 				  	 Último login:
 				  	 <h:outputLabel value="#{usuarioBeanView.ultimoAcesso}"
 				  	  id="saidaUltimoAcesso">
						<f:convertDateTime locale="pt_BR" pattern="dd/MM/yyyy HH:mm:ss"
						dateStyle="long" timeStyle="full" timeZone="GMT-03:00"/> 				  	 	
 				  	 </h:outputLabel>
 				  	 <br id="quebraUltimoAcesso"/>
 				  	 <br id="quebraUltimoAcesso2"/>
 				  	 <a href="#" onclick="javascript:logout('#{request.contextPath}')">Sair</a>
				</span>
				
				 
			</div>

			<div id="menu">
				<span id="iniciarmenu"> <h:graphicImage library="img"
						name="iconemenu.png" styleClass="bordaimagem" id="iconemenu">
						  
						</h:graphicImage>
				</span>
			</div>
			
			<div id="corpo" class="corpo">
			   <ui:insert name="corpo" />
			</div>
			
 				<div id="barramenu">
 						<p:tieredMenu id="menuEsquerdo"
 						 style="width:185px; border: none; background:none; color:#000;">
 							
  							<!-- <sec:ifAnyGranted roles="USER"> -->
 								
 								<p:submenu label="Cedulas" id="subMenuCedula">
 									<!-- <sec:ifAnyGranted roles="USER"> -->
	 									<p:menuitem value="Listar Estoque de Cédulas" id="menuEstoqueCedulas"
	 									  action="/recarga/rec_cedulas.jsf?faces-redirect=true">
	 									
	 									</p:menuitem>
	 									<p:menuitem value="Reabastecer Cedulas" id="menuRecarregarCedulas"
	 									  action="/recarga/rec_cedulas.jsf?faces-redirect=true">
	 									
	 									</p:menuitem>
 									<!-- </sec:ifAnyGranted> -->
 								</p:submenu>
 								
 							<!-- </sec:ifAnyGranted> -->
 							
 							
 							
 							<!-- <sec:ifAnyGranted roles="USER"> -->
	 						    <p:menuitem value="Saque" id="menuSaque"
	 						    onclick="redirecionarPagina('#{request.contextPath}', '/restrito/principal');"
	 						    ajax="true" />
 						    <!-- </sec:ifAnyGranted> -->
 						    
 							
 							<p:menuitem onclick="javascript:logout('#{request.contextPath}');"
 							value="Sair" id="menusair" ajax="true"/>
 						</p:tieredMenu>
 				</div>

			</div>
			
 			<p:dialog widgetVar="enviarMsgDialog" id="alterarMsgDialog" width="800"
				modal="true" resizable="false" height="360"
				header="Enviar menssagem" appendToBody="false" dynamic="true">
			</p:dialog>
			
 		<p:dialog widgetVar="alterarSenhaDialog" id="alterarSenhaDialog" width="240" modal="true" resizable="false" 
 			height="170" header="Alterar Senha" dynamic="true" appendToBody="false">
 			corpo	
 		</p:dialog>	
 					
	</h:body>
</h:form>	

 <script type="text/javascript" charset="UTF-8">
	 carregarIdElementosPagina();
 </script>

</sec:isAuthenticated>	
</html>